services:
  r-oneapi:
    build:
      context: .
      dockerfile: docker/oraclelinux97-r453/Dockerfile
    volumes:
      - .:/workspace/sbyadanear
    environment:
      MKL_DYNAMIC: "FALSE"
    tty: true
    stdin_open: true
