# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Verificação de interrupção do usuário
#' @description Encaminha a checagem cooperativa de interrupção para a API do R.
#' @return Valor nulo do R.
NULL

#' @title Parâmetros nativos de Z-Score
#' @description Calcula médias e desvios-padrão amostrais por coluna com aceleração vetorial quando disponível.
#' @param x_matrix Matriz double de entrada.
#' @return Lista com centros e escalas.
NULL

#' @title Transformação Z-Score vetorizada
#' @description Aplica ou reverte a padronização Z-Score utilizando primitivas vetoriais oneMath quando habilitadas.
#' @param x_matrix Matriz double de entrada.
#' @param centers Vetor double de médias.
#' @param scales Vetor double de desvios-padrão.
#' @param reverse Indicador lógico de reversão.
#' @return Matriz double transformada.
NULL

#' @title Síntese ADASYN nativa por linha
#' @description Gera observações sintéticas a partir da interpolação entre instâncias minoritárias e seus vizinhos.
#' @return Matriz double sintética.
NULL

#' @title Seleção NearMiss acelerada
#' @description Seleciona exemplos majoritários por médias de distância usando ordenação parcial oneDPL quando habilitada.
#' @return Vetor inteiro de índices retidos.
NULL

#' @title Síntese ADASYN nativa por coluna
#' @description Gera observações sintéticas em layout favorável à localidade de colunas.
#' @return Matriz double sintética.
NULL

#' @title Remoção do próprio vizinho
#' @description Remove o índice da própria observação de uma matriz KNN registrada.
#' @return Matriz inteira de vizinhos filtrados.
NULL

#' @title KNN bruto nativo
#' @description Executa KNN euclidiano exato com distância vetorizada e ordenação parcial.
#' @return Lista com índices e distâncias.
NULL

#' @title Índices KNN brutos nativos
#' @description Executa KNN euclidiano exato retornando apenas índices.
#' @return Lista com matriz de índices.
NULL

#' @title Distâncias KNN brutas nativas
#' @description Executa KNN euclidiano exato retornando apenas distâncias.
#' @return Lista com matriz de distâncias.
NULL

#' @title KNN bruto nativo parametrizado
#' @description Executa KNN euclidiano exato interno com controle de retorno e self-neighbor.
#' @return Lista com matrizes KNN solicitadas.
NULL

#' @title NearMiss bruto fundido
#' @description Calcula distâncias KNN e seleciona exemplos majoritários sem materializar a matriz intermediária no R.
#' @return Vetor inteiro de índices retidos.
NULL

#' @title Concatenação nativa de matrizes double
#' @description Empilha duas matrizes double por linhas preservando nomes de colunas quando disponíveis.
#' @return Matriz double concatenada.
NULL

#' @title Z-Score populacional nativo Fortran
#' @description Calcula media e desvio padrao populacionais via motor Fortran AVX-512.
#' @param x_matrix Matriz double transposta (P x N).
#' @return Lista com vetores means e sds.
NULL

#' @title Aplicacao de Z-Score nativo Fortran
#' @description Aplica padronizacao Z-Score via motor Fortran AVX-512.
#' @param x_matrix Matriz double transposta (P x N).
#' @param means Vetor double de medias.
#' @param sds Vetor double de desvios padrao.
#' @return Matriz double padronizada.
NULL

#' @title Reversao de Z-Score nativo Fortran
#' @description Reverte padronizacao Z-Score via motor Fortran AVX-512.
#' @param x_matrix Matriz double transposta (P x N).
#' @param means Vetor double de medias.
#' @param sds Vetor double de desvios padrao.
#' @return Matriz double na escala original.
NULL

#' @title Concatenacao de matrizes nativa Fortran
#' @description Empilha duas matrizes P x N por colunas via motor Fortran com OpenMP.
#' @param a_matrix Primeira matriz double (P x N1).
#' @param b_matrix Segunda matriz double (P x N2).
#' @return Matriz double (P x (N1+N2)).
NULL

#' @title Registro nativo do pacote
#' @description Registra as rotinas .Call e desativa resolução dinâmica de símbolos.
#' @param dll Ponteiro para a biblioteca dinâmica carregada pelo R.
NULL

